name: Scope

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Scope for Python
        uses: undefinedlabs/scope-for-python-action@master
        with:
          dsn: ${{secrets.SCOPE_DSN}}
          command: ./manage.py test
